const nationInfo = {
    "rome": {
        "name": "Rome",
        "empire_name": "Roman Empire",
        "color": "#af0404",
        "city_names": [
            "Ostia",
            "Antium",
            "Cumae",
            "Aquileia",
            "Ravenna",
            "Puteoli",
            "Arretium",
            "Mediolanum",
            "Lugdunum",
            "Arpinum",
            "Setia",
            "Velitrae",
            "Durocortorum",
            "Brundisium",
            "Caesaraugusta",
            "Palmyra",
            "Hispalis",
            "Caesarea",
            "Artaxata",
            "Paphos",
            "Salonae",
            "Eburacum",
            "Lauriacum",
            "Verona",
            "Colonia Agrippina",
            "Narbo",
            "Tingi",
            "Sarmizegetusa",
            "Sirmium",
            "Pompeii"
        ],
    },
    "thrace": {
        "name": "Thrace",
        "empire_name": "Thracian Empire",
        "color": "#636473",
        "city_names": [
            "Cabyle",
            "Helis",
            "Seuthopolis",
            "Pistiros",
            "Sborjanovo",
        ],
    },
    "parthia": {
        "name": "Partia",
        "empire_name": "Partian Empire",
        "color": "#eaa329",
        "city_names": [
            "Nisa",
            "Hecatompylos",
            "Merv",
            "Ecbatana",
            //"Ctesiphon",
            "Seleucia",
            "Nicephorium",
            "Nisibis",
            "Dura-Europos",
            "Rhagae",
            "Charax Spasinu"
        ],
    },
    "armenia": {
        "name": "Armenia",
        "empire_name": "Armenian Empire",
        "color": "#ae5a3d",
        "city_names": [
            "Artashat",
            "Tigranakert",
            "Vagharshapat",
            "Aza",
            "Nicopolis",
            "Carcathiocerta",
            "Tigranocerta",
            "Artaxata"
        ],
    },  
}